// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvlnZaxRpWcmun5rTMnxdmVc7dpIQ5HIo',
    appId: '1:532906047162:web:2e707c267f2285dd2cb483',
    messagingSenderId: '532906047162',
    projectId: 'flutterfireauth-cf4f9',
    authDomain: 'flutterfireauth-cf4f9.firebaseapp.com',
    storageBucket: 'flutterfireauth-cf4f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdtRJ0klDGe6EQSf7lAcMz7wlNGKV5FlM',
    appId: '1:532906047162:android:2b178cb68b2a789c2cb483',
    messagingSenderId: '532906047162',
    projectId: 'flutterfireauth-cf4f9',
    storageBucket: 'flutterfireauth-cf4f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_6riu3H16qioQ--o-u_e3vdap6aErDC4',
    appId: '1:532906047162:ios:9b89ca610ab9d5412cb483',
    messagingSenderId: '532906047162',
    projectId: 'flutterfireauth-cf4f9',
    storageBucket: 'flutterfireauth-cf4f9.appspot.com',
    iosClientId: '532906047162-a1o4fs539acl029ij2bptd63vucho7lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFireAuthentication',
  );
}
